import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Zap, Layers, Share2, Crown, ChevronRight, Info, 
  TrendingUp, Users, Target, Activity, ShieldCheck
} from 'lucide-react';
import { useGameStore } from '../store/gameStore.js';
import { useContract } from '../hooks/useContract.js';
import { formatNumber, formatBNB, shortAddr } from '../utils/format.js';
import { useBnbPrice } from '../hooks/useBnbPrice.js';
import { CONTRACTS } from '../config/constants.js';

export default function DashboardScreen() {
  const {
    walletAddress, hasNode, nodeId, nodeActive, nodeTier,
    totalEarned, pendingReward, teamSize, directRefs,
    poolClaimable, poolQual, localReward, streak, isConnected,
    conversionHistory, isFreeActive, globalStats
  } = useGameStore();
  
  const { loadNodeData, connectWallet, claimPool, fetchTeamCounts, registerPool } = useContract();
  const bnbPrice = useBnbPrice();
  
  const [levelCounts, setLevelCounts] = useState([]);
  const [selectedIncome, setSelectedIncome] = useState(null);

  const usd = (bnb) => bnbPrice > 0 ? <span style={{ fontSize: 11, fontWeight: 700, color: '#4FC3F7', display: 'block', marginTop: 2 }}>≈ ${(parseFloat(bnb || 0) * bnbPrice).toFixed(2)}</span> : null;

  const INCOME_TYPES = [
    {
      id: 'direct',
      name: 'DIRECT REWARD',
      share: '10.0%',
      color: '#FF7043',
      icon: <Zap size={18} />,
      desc: 'Earn 10% instantly from every node activation and tier upgrade performerd by your direct referrals. Infinite width, applies to all 18 tiers.'
    },
    {
      id: 'layer',
      name: 'LAYER YIELD',
      share: '14.95%',
      color: '#4FC3F7',
      icon: <Layers size={18} />,
      desc: 'Deep penetration rewards across 17 layers. 1.5% for L1-5, 1.0% for L6-10, and 0.35% for L11-17. Requires 2 direct referrals to unlock deep depth.'
    },
    {
      id: 'matrix',
      name: 'MATRIX CASCADE',
      share: '70.0%',
      color: 'var(--neon-lime)',
      icon: <Share2 size={18} />,
      desc: 'Our flagship algorithm. Targeted 70% binary payload with a 10-level fallback split. Ensures 100% distribution even if parents are unqualified.'
    },
    {
      id: 'pool',
      name: 'GLOBAL POOL',
      share: '5.05%',
      color: '#FFD700',
      icon: <Crown size={18} />,
      desc: 'Lifetime royalty sharing from 5% of all global platform volume. Passive yield generated by every single transaction in the ecosystem.'
    }
  ];


  useEffect(() => {
    if (walletAddress) {
      loadNodeData(walletAddress);
    }
  }, [walletAddress, loadNodeData]);

  useEffect(() => {
    if (isConnected && nodeId) {
      fetchTeamCounts(nodeId).then(setLevelCounts);
    }
  }, [isConnected, nodeId, fetchTeamCounts]);

  const calcDirects = levelCounts.length > 0 ? levelCounts[0] : (directRefs || 0);
  const calcTotal = levelCounts.length > 0 ? levelCounts.reduce((a, b) => a + b, 0) : (teamSize || 0);

  return (
    <div className="page page-dashboard">
      {/* Hero Header */}
      <div style={{ padding: '20px 0 32px', textAlign: 'center' }}>
        <div style={{ position: 'relative', width: '90px', height: '90px', margin: '0 auto 16px' }}>
          <div style={{ 
            width: '100%', height: '100%', 
            background: 'var(--bg-card)', 
            borderRadius: '24px', 
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '36px',
            border: `2px solid ${hasNode && nodeActive ? 'var(--neon-lime)' : '#FF3B30'}`,
            boxShadow: hasNode && nodeActive ? '0 0 20px rgba(203, 255, 1, 0.2)' : 'none'
          }}>
            {hasNode ? '⬡' : '👤'}
          </div>
          {hasNode && nodeActive && (
            <div style={{ 
              position: 'absolute', bottom: -5, right: -5,
              width: '24px', height: '24px', borderRadius: '50%',
              background: 'var(--neon-lime)', border: '4px solid var(--bg-dark)',
              animation: 'pulse 2s infinite'
            }} />
          )}
        </div>
        <h2 style={{ fontSize: '26px', fontWeight: 900, letterSpacing: '-0.02em', textShadow: '0 0 10px rgba(255,255,255,0.1)' }}>
          {hasNode ? `NODE #${nodeId}` : (isFreeActive ? 'FREE OPERATIVE' : 'GUEST OPERATOR')}
        </h2>
        <div style={{ 
          display: 'inline-flex', padding: '4px 12px', borderRadius: '20px', 
          background: 'rgba(255,255,255,0.05)', marginTop: 8, gap: 8, alignItems: 'center'
        }}>
          <span style={{ fontSize: '11px', fontWeight: 800, color: '#FF5252' }}>
            {isConnected ? shortAddr(walletAddress) : 'NOT CONNECTED'}
          </span>
          {isConnected && <span style={{ color: 'var(--neon-lime)', fontSize: '10px' }}>●</span>}
        </div>
      </div>

        {/* Total Earned - Main Highlight with Animation */}
        <motion.div 
          whileHover={{ scale: 1.02 }}
          className="partner-card" 
          style={{ 
            flexDirection: 'column', alignItems: 'center', margin: '0 0 12px', padding: '24px 20px',
            background: 'linear-gradient(135deg, rgba(203,255,1,0.12) 0%, rgba(203,255,1,0.03) 100%)',
            border: '1px solid rgba(203,255,1,0.25)',
            boxShadow: '0 10px 30px rgba(0,0,0,0.3)'
          }}
        >
          <span style={{ fontSize: '10px', fontWeight: 800, color: '#A3FF12', letterSpacing: 2, marginBottom: 8 }}>ALGORITHMIC NODE FLOW (BNB)</span>
          <span style={{ fontSize: '36px', fontWeight: 950, color: '#fff', textShadow: '0 0 20px rgba(203,255,1,0.4)' }}>{formatBNB(totalEarned)}</span>
          {usd(totalEarned)}
        </motion.div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 32 }}>
          {[
            { label: 'SELF LEVEL', val: `TIER ${nodeTier}`, sub: formatBNB(poolQual.totalDeposited), color: '#FFB74D' },
            { label: 'AIP COINS', val: formatNumber(localReward), sub: 'Mining Asset', color: '#FFD700' },
            { label: 'UNCLAIMED', val: formatBNB(pendingReward), sub: 'Node Balance', color: 'var(--neon-lime)' },
            { label: 'POOL ROI', val: formatBNB(poolClaimable), sub: 'Global Payout', color: '#4FC3F7' }
          ].map((item, i) => (
            <motion.div 
              key={i}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: i * 0.05 }}
              className="partner-card" 
              style={{ flexDirection: 'column', alignItems: 'flex-start', margin: 0, padding: 16, border: '1px solid rgba(255,255,255,0.05)' }}
            >
              <span style={{ fontSize: '10px', fontWeight: 800, color: item.color, letterSpacing: 0.5 }}>{item.label}</span>
              <span style={{ fontSize: '18px', fontWeight: 900, color: '#fff', marginTop: 4 }}>{item.val}</span>
              <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.4)', fontWeight: 700 }}>{item.sub}</span>
            </motion.div>
          ))}
        </div>

        {/* ALGORITHMIC INCOME ARCHITECTURE - NEW INTERACTIVE SECTION */}
        <h3 style={{ fontSize: '13px', fontWeight: 800, color: '#FFFFFF', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
          <Activity size={16} color="#A3FF12" /> INCOME DISTRIBUTION ARCHITECTURE
        </h3>
        
        <div style={{ 
          background: 'var(--bg-card)', 
          borderRadius: '24px', 
          padding: '24px', 
          border: '1px solid rgba(203, 255, 1, 0.1)',
          marginBottom: 32,
          position: 'relative',
          overflow: 'hidden'
        }}>
          {/* Animated SVG Backdrop */}
          <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', opacity: 0.1, pointerEvents: 'none' }}>
            <svg width="100%" height="100%" viewBox="0 0 400 400">
              <motion.circle 
                cx="200" cy="200" r="100" fill="none" stroke="var(--neon-lime)" strokeWidth="0.5" 
                animate={{ r: [100, 110, 100], opacity: [0.1, 0.3, 0.1] }}
                transition={{ duration: 4, repeat: Infinity }}
              />
              <line x1="200" y1="200" x2="0" y2="0" stroke="white" strokeWidth="0.5" />
              <line x1="200" y1="200" x2="400" y2="0" stroke="white" strokeWidth="0.5" />
              <line x1="200" y1="200" x2="0" y2="400" stroke="white" strokeWidth="0.5" />
              <line x1="200" y1="200" x2="400" y2="400" stroke="white" strokeWidth="0.5" />
            </svg>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, position: 'relative', zIndex: 2 }}>
            {INCOME_TYPES.map((type) => (
              <motion.div
                key={type.id}
                layout
                onClick={() => setSelectedIncome(selectedIncome === type.id ? null : type.id)}
                whileTap={{ scale: 0.96 }}
                style={{
                  background: 'rgba(255,255,255,0.03)',
                  border: `1px solid ${selectedIncome === type.id ? type.color : 'rgba(255,255,255,0.07)'}`,
                  borderRadius: '16px',
                  padding: '16px',
                  cursor: 'pointer',
                  boxShadow: selectedIncome === type.id ? `0 0 15px ${type.color}20` : 'none'
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 }}>
                  <div style={{ 
                    padding: 8, borderRadius: '10px', background: `${type.color}15`, color: type.color 
                  }}>
                    {type.icon}
                  </div>
                  <span style={{ fontSize: '18px', fontWeight: 950, color: type.color, textShadow: `0 0 10px ${type.color}40` }}>{type.share}</span>
                </div>
                
                <div style={{ fontSize: '10px', fontWeight: 900, color: '#fff', letterSpacing: 0.5 }}>{type.name}</div>
                <div style={{ fontSize: '9px', color: 'rgba(255,255,255,0.4)', fontWeight: 800, marginTop: 4, display: 'flex', alignItems: 'center', gap: 4 }}>
                  <Info size={10} /> TAP FOR SPECS
                </div>
                
                <AnimatePresence>
                  {selectedIncome === type.id && (
                    <motion.div 
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      style={{ marginTop: 16, overflow: 'hidden' }}
                    >
                      <p style={{ fontSize: '11px', lineHeight: 1.6, color: '#ddd', margin: 0, fontWeight: 500 }}>
                        {type.desc}
                      </p>
                      <div style={{ 
                        marginTop: 12, paddingTop: 12, borderTop: '1px solid rgba(255,255,255,0.1)',
                        display: 'flex', alignItems: 'center', gap: 8, color: type.color, fontSize: '10px', fontWeight: 900
                      }}>
                        <ShieldCheck size={12} /> PROTOCOL VERIFIED
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Reward Pool Command Center */}
      <h3 style={{ fontSize: '13px', fontWeight: 800, color: '#FF5252', marginBottom: 12 }}>COMMAND: REWARD POOL</h3>
      <div className="partner-card" style={{ flexDirection: 'column', padding: 20, marginBottom: 24, background: 'rgba(203, 255, 1, 0.02)', border: '1px solid rgba(203, 255, 1, 0.1)' }}>
        <div style={{ width: '100%', display: 'flex', justifyContent: 'space-between', marginBottom: 20, alignItems: 'center' }}>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <span style={{ fontSize: '10px', fontWeight: 800, color: '#FFFFFF' }}>QUALIFYING FOR</span>
            <span style={{ fontSize: '18px', fontWeight: 900, color: 'var(--neon-lime)' }}>{poolQual.poolName.toUpperCase()}</span>
          </div>
          <div style={{ textAlign: 'right' }}>
            <span style={{ fontSize: '10px', fontWeight: 800, color: '#FFB74D' }}>STATUS</span>
            <div style={{ fontSize: '14px', fontWeight: 900, color: poolQual.isPoolQualified ? 'var(--neon-lime)' : '#FF3B30' }}>
              {poolQual.isPoolQualified ? 'QUALIFIED' : 'PENDING'}
            </div>
          </div>
        </div>

        {/* Qualification Bars */}
        <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: 16 }}>
          {[
            { label: 'DIRECT FRIENDS', current: calcDirects, missing: poolQual.missingDirects },
            { label: 'SELF LEVEL', current: nodeTier, missing: poolQual.missingTier },
            { label: 'TOTAL TEAM', current: calcTotal, missing: poolQual.missingTeam },
          ].map(req => {
            const total = req.current + req.missing;
            const progress = total === 0 ? 0 : Math.min(100, (req.current / total) * 100);
            return (
              <div key={req.label} style={{ width: '100%' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
                  <span style={{ fontSize: '10px', fontWeight: 800, color: '#FFD700' }}>{req.label}</span>
                  <span style={{ fontSize: '10px', fontWeight: 900, color: progress >= 100 ? 'var(--neon-lime)' : '#fff' }}>
                    {req.current} / {total}
                  </span>
                </div>
                <div style={{ width: '100%', height: '6px', background: 'rgba(255,255,255,0.05)', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{ width: `${progress}%`, height: '100%', background: progress >= 100 ? 'var(--neon-lime)' : '#555', transition: 'width 1s ease' }} />
                </div>
              </div>
            );
          })}
        </div>

        {/* Manual Registration Button shown when qualified for next tier */}
        {poolQual.isPoolQualified && poolQual.poolName !== "Gold" && (
          <button 
            className="giant-btn" 
            style={{ 
              marginTop: 24, 
              background: 'var(--neon-lime)', 
              color: '#000', 
              height: 44, 
              fontSize: 13,
              boxShadow: '0 0 20px rgba(203, 255, 1, 0.4)'
            }}
            onClick={() => registerPool(nodeId)}
          >
            ACTIVATE {poolQual.poolName === 'None' ? 'BRONZE' : poolQual.poolName === 'Bronze' ? 'SILVER' : 'GOLD'} POOL
          </button>
        )}


        {poolClaimable > 0 && (
          <button 
            className="giant-btn" 
            style={{ marginTop: 24, background: 'var(--neon-lime)', color: '#000', height: 44, fontSize: 13 }}
            onClick={() => claimPool(nodeId)}
          >
            CLAIM POOL REWARDS ({formatBNB(poolClaimable)})
          </button>
        )}
      </div>

      {/* Network Stats Card */}
      <div className="partner-card" style={{ flexDirection: 'column', padding: 20, marginBottom: 32 }}>
        <div style={{ width: '100%', display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
          <span style={{ fontSize: '14px', fontWeight: 800 }}>NETWORK GROWTH</span>
          <span style={{ fontSize: '11px', fontWeight: 900, color: 'var(--neon-lime)' }}>LEVEL {nodeTier}</span>
        </div>
        <div style={{ width: '100%', display: 'flex', gap: 32 }}>
          <div className="flex-column">
            <span style={{ fontSize: '24px', fontWeight: 900 }}>{calcDirects}</span>
            <span style={{ fontSize: '10px', fontWeight: 700, color: '#A3FF12' }}>DIRECT FRIENDS</span>
          </div>
          <div className="flex-column">
            <span style={{ fontSize: '24px', fontWeight: 900 }}>{calcTotal}</span>
            <span style={{ fontSize: '10px', fontWeight: 700, color: '#4FC3F7' }}>TOTAL NETWORK</span>
          </div>
        </div>
        <div style={{ width: '100%', height: '6px', background: 'rgba(255,255,255,0.05)', borderRadius: '3px', marginTop: 20, overflow: 'hidden' }}>
          <div style={{ width: '45%', height: '100%', background: 'var(--neon-lime)', boxShadow: '0 0 10px var(--neon-lime)' }} />
        </div>
      </div>

      {/* Protocol Global Stats Card */}
      <h3 style={{ fontSize: '13px', fontWeight: 800, color: '#FF5252', marginBottom: 12, marginTop: 32 }}>PROTOCOL GLOBAL INSIGHTS</h3>
      <div className="partner-card" style={{ padding: '24px 20px', marginBottom: 24, background: 'linear-gradient(180deg, rgba(203,255,1,0.05) 0%, transparent 100%)', border: '1px solid rgba(203,255,1,0.1)' }}>
        <div style={{ width: '100%', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', textAlign: 'center' }}>
          <div>
            <div style={{ fontSize: '20px', fontWeight: 900, color: 'var(--neon-lime)' }}>
              {parseFloat(globalStats?.total_volume_bnb || 0).toFixed(2)}
            </div>
            <div style={{ fontSize: '9px', fontWeight: 800, color: '#FFFFFF', marginTop: 2 }}>TOTAL VOL (BNB)</div>
            {bnbPrice > 0 && <div style={{ fontSize: '9px', fontWeight: 700, color: '#4FC3F7', marginTop: 1 }}>≈ ${(parseFloat(globalStats?.total_volume_bnb || 0) * bnbPrice).toFixed(0)}</div>}
          </div>
          <div>
            <div style={{ fontSize: '20px', fontWeight: 900 }}>{globalStats?.active_nodes || 0}</div>
            <div style={{ fontSize: '9px', fontWeight: 800, color: '#FFB74D', marginTop: 4 }}>ACTIVE OPERATORS</div>
          </div>
          <div>
            <div style={{ fontSize: '20px', fontWeight: 900 }}>{globalStats?.total_users || 0}</div>
            <div style={{ fontSize: '9px', fontWeight: 800, color: '#FFD700', marginTop: 4 }}>TOTAL NETWORK</div>
          </div>
        </div>
      </div>

      {/* Token Conversion History */}
      <h3 style={{ fontSize: '13px', fontWeight: 800, color: '#A3FF12', marginBottom: 12, marginTop: 32 }}>HISTORY: TOKEN CONVERSION</h3>
      <div className="partner-card" style={{ flexDirection: 'column', padding: 20, marginBottom: 32 }}>
        {conversionHistory.length > 0 ? (
          <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: 16 }}>
            {conversionHistory.map((item, idx) => (
              <div key={idx} style={{ 
                display: 'flex', justifyContent: 'space-between', alignItems: 'center', 
                paddingBottom: 12, borderBottom: idx !== conversionHistory.length - 1 ? '1px solid rgba(255,255,255,0.05)' : 'none' 
              }}>
                <div style={{ display: 'flex', flexDirection: 'column' }}>
                  <span style={{ fontSize: '13px', fontWeight: 800 }}>{item.name}</span>
                  <span style={{ fontSize: '10px', color: '#4FC3F7' }}>{new Date(item.created_at).toLocaleDateString()}</span>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '14px', fontWeight: 900, color: 'var(--neon-lime)' }}>{formatNumber(item.mined_amount)} 🪙</div>
                  <div style={{ fontSize: '10px', color: '#FFB74D', fontWeight: 800 }}>CONVERTED</div>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div style={{ padding: '20px 0', textAlign: 'center', color: '#FF5252', width: '100%' }}>
            <div style={{ fontSize: '24px', marginBottom: 8 }}>📜</div>
            <div style={{ fontSize: '11px', fontWeight: 800 }}>NO CONVERSIONS RECORDED YET</div>
          </div>
        )}
      </div>

      {/* Wallet Actions */}
      {!isConnected ? (
        <button className="giant-btn" style={{ position: 'relative', bottom: 0, marginBottom: 32 }} onClick={connectWallet}>
          CONNECT BSC WALLET
        </button>
      ) : (
        <div className="partner-card" style={{ padding: 16, justifyContent: 'space-between', background: 'rgba(255,59,48,0.05)', border: '1px solid rgba(255,59,48,0.1)' }}>
          <span style={{ fontSize: '13px', fontWeight: 800, color: '#FF3B30' }}>CONNECTED WALLET</span>
          <span style={{ fontSize: '12px', fontWeight: 700 }}>{shortAddr(walletAddress)}</span>
        </div>
      )}

      {/* Contract Verification Section */}
      <h3 style={{ fontSize: '13px', fontWeight: 800, color: '#FFFFFF', margin: '32px 0 12px', textAlign: 'center' }}>
        SMART CONTRACT VERIFICATION
      </h3>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, paddingBottom: 60 }}>
        {[
          { name: 'CORE', addr: CONTRACTS.AIPCORE },
          { name: 'VIEW', addr: CONTRACTS.AIPVIEW },
          { name: 'POOL', addr: CONTRACTS.REWARDPOOL },
        ].map(c => (
          <a 
            key={c.name}
            href={`https://bscscan.com/address/${c.addr}`}
            target="_blank" rel="noreferrer"
            style={{ 
              background: 'var(--bg-card)', padding: '16px 8px', 
              borderRadius: '16px', textAlign: 'center', textDecoration: 'none',
              border: '1px solid rgba(255,255,255,0.05)'
            }}
          >
            <div style={{ fontSize: '10px', fontWeight: 900, color: '#fff', marginBottom: 4 }}>{c.name}</div>
            <div style={{ fontSize: '9px', fontWeight: 700, color: 'var(--neon-lime)' }}>{shortAddr(c.addr)}</div>
          </a>
        ))}
      </div>
    </div>
  );
}
